Project gymjinni_class {
  datebase_type: 'PostgreSQL'
  Note: 'gymjinni class management database schema'
}

Table class.class {
  id serial [pk]
  created_by int // [ref: > user.user.id ]
  description varchar [not null]
  start_time timestamptz [not null]
  end_time timestamptz [not null]
  min_hdcnt int
  max_hdcnt int
}
