apiVersion: v1
kind: ConfigMap
metadata:
  name: gym-jinni-config
  namespace: gym-jinni
data:
  DBURL: "postgresql://root:gj@postgres:5432/gj?sslmode=disable&search_path=public"
  POSTGRES_HOST: "postgres"
  POSTGRES_PORT: "5432"
  POSTGRES_DB: "gj"
  CSR_SERVICE_GRPC: "main-service:8080"
  CSR_SERVICE_HTTP: "main-service:8081"
  MAIN_SERVICE_GRPC: "main-service:8080"
  MAIN_SERVICE_HTTP: "main-service:8081"

